name: link_task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  equatable: ^2.0.5
  dio: ^5.3.2
  freezed_annotation: ^2.4.1
  flutter_phoenix: ^1.1.1
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  flutter_svg: 2.0.0
  dartz: ^0.10.1
  intl: ^0.18.1
  url_launcher: 6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

